FROM node:20-alpine AS dev

WORKDIR /app

# Install all dependencies including dev dependencies
COPY package*.json ./
RUN npm i

# Copy source code
COPY . .

# Expose dev port (change as needed)
EXPOSE 9002

# Start the app with nodemon for live reload
CMD ["npm", "start"]
