apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

#secretGenerator:
#  - name: google-api-secret
#    literals:
#      - GOOGLE_KEY=dummy
#    type: Opaque



#generatorOptions:
#  disableNameSuffixHash: true
