name: Publish Image To ECR 

run-name: Triggered branch ${{ github.ref_name }} by @${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  GITHUB_SHA: ${{ github.sha }}
  REGISTRY_HOSTNAME: ${{ vars.REGISTRY_HOSTNAME }}
  IMAGE: track24

jobs:
  setup-build-publish:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
    
      # Build the Docker image
      - name: Build Docker Image
        run: |-
          docker build \
            -f Dockerfile \
            --tag "$REGISTRY_HOSTNAME/$IMAGE:$GITHUB_SHA" \
            .
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      # Push the Docker image to AWS Container Registry
      - name: Publish To ECR
        run: |-
          docker push "$REGISTRY_HOSTNAME/$IMAGE:$GITHUB_SHA"
          
