name: Create and publish a Docker image
on:
  push:
    branches:
      - main
env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  REGISTRY:   ${{ vars.AWS_REGISTRY }}
  REPOSITORY: devops-tech-test
  IMAGE_NAME: devops-tech-test

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create Amazon ECR
        id: create-ecr 
        env: 
          REPOSITORY: ${{ env.REPOSITORY }}
        run: |
          aws ecr create-repository --repository-name $REPOSITORY || echo "Already exists"

# https://docs.docker.com/build/ci/github-actions/cache/#local-cache
      - name: Cache Docker layers
        id: cache-docker
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push
        id: build-docker
        uses: docker/build-push-action@v6
        with:
          context: app
          file: Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest  # TODO: Use Github tags as labels      
          cache-from: type=local,src=${{ runner.temp }}/.buildx-cache
          cache-to: type=local,dest=${{ runner.temp }}/.buildx-cache-new,mode=max

      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf ${{ runner.temp }}/.buildx-cache
          mv ${{ runner.temp }}/.buildx-cache-new ${{ runner.temp }}/.buildx-cache
